<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2023 (x64) (http://www.altova.com) by Conny Graumans (AgroConnect) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="addresses" type="addresses"/>
	<xs:complexType name="addresses">
		<xs:sequence>
			<xs:element name="postalCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="cytyName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="streetName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="streetNumber" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="country" type="countryCodeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Country codes: 2 letter ISO 3166.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="countryName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="postalBoxId" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="allocations" type="allocations"/>
	<xs:complexType name="allocations">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="type" type="codeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="resourceId" type="codeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="batchId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="quantityAbsolute" type="measurementType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="quantityRate" type="measurementType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="characteristics" type="characteristicType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="assets" type="assets"/>
	<xs:complexType name="assets">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="startDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
			<xs:element name="endDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
			<xs:element name="characteristics" type="characteristicType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="certificats" type="certificats" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="classifications" type="classifications" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="contracts" type="contracts" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="observations" type="observations" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="parties" type="parties" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="assetTypeCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PLOT"/>
			<xs:enumeration value="CROP"/>
			<xs:enumeration value="BUILDING"/>
			<xs:enumeration value="DITCH"/>
			<xs:enumeration value="GREENHOUSE"/>
			<xs:enumeration value="STORAGE"/>
			<xs:enumeration value="MACHINE"/>
			<xs:enumeration value="BATCH"/>
			<xs:enumeration value="BLOCK">
				<xs:annotation>
					<xs:documentation>Part of a greenhouse (Dutch term: afdeling).
Each bloch has a fixes xyz-reference-point. The Dutch term for this reference point is: Hortivationpoint.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="batchRecord" type="batchRecord"/>
	<xs:complexType name="batchRecord">
		<xs:sequence/>
	</xs:complexType>
	<xs:element name="binaryFiles" type="binaryFiles"/>
	<xs:complexType name="binaryFiles">
		<xs:sequence>
			<xs:element name="access" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="acessAvailabilitySpecifiedPeriod" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="authorName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="characterSetCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="encodingCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="fileName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="includedBinaryObject" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="mimeCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="sizeMeasure" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="titel" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="uriid" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="versionId" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="binaryObjectType" type="binaryObjectType"/>
	<xs:complexType name="binaryObjectType">
		<xs:sequence>
			<xs:element name="charactersetCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="encodingCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="filename" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="format" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="mimeCode" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="uri" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="block" type="block"/>
	<xs:complexType name="block">
		<xs:annotation>
			<xs:documentation>Part of a greenhouse (Dutch term: afdeling).
Each bloch has a fixes xyz-reference-point. The Dutch term for this reference point is: Hortivationpoint.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="assets">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="border" type="border"/>
	<xs:complexType name="border">
		<xs:sequence>
			<xs:element name="exterior" type="exterior" minOccurs="1" maxOccurs="1"/>
			<xs:element name="interior" type="interior" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="buyers" type="buyers"/>
	<xs:complexType name="buyers">
		<xs:complexContent>
			<xs:extension base="parties">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="certificats" type="certificats"/>
	<xs:complexType name="certificats">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="issueDate" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="startDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="endDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="certifiers" type="certifiers" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="certifiers" type="certifiers"/>
	<xs:complexType name="certifiers">
		<xs:complexContent>
			<xs:extension base="parties">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="characteristic" type="characteristic"/>
	<xs:complexType name="characteristic">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="value" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="valueUnit" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="characteristicType" type="characteristicType"/>
	<xs:complexType name="characteristicType">
		<xs:sequence>
			<xs:element name="code" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="codeListId" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="value" type="measurementType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="issueDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="startDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="endDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="classifications" type="classifications"/>
	<xs:complexType name="classifications">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="issueDate" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="startDate" type="xs:dateTime" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>E.g.: derogation,organic farming, etc.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="endDate" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="type" type="codeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="climatObservation" type="climatObservation"/>
	<xs:complexType name="climatObservation">
		<xs:complexContent>
			<xs:extension base="observations">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="codeType" type="codeType"/>
	<xs:complexType name="codeType">
		<xs:sequence>
			<xs:element name="codeListId" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="code" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="issueingPartyId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="uri" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="compositions" type="compositions"/>
	<xs:complexType name="compositions">
		<xs:sequence>
			<xs:element name="ingredientId" type="codeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Code list: nl.cl363</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ingredientName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="quantity" type="measurementType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="contractors" type="contractors"/>
	<xs:complexType name="contractors">
		<xs:complexContent>
			<xs:extension base="parties">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="contracts" type="contracts"/>
	<xs:complexType name="contracts">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="issueDate" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="startDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="endDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="buyers" type="buyers" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="countryCodeType">
		<xs:annotation>
			<xs:documentation>Country codes: 2 letter ISO 3166.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="NL">
				<xs:annotation>
					<xs:documentation>NL = Netherlands</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="BE">
				<xs:annotation>
					<xs:documentation>BE = Belgium</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DE">
				<xs:annotation>
					<xs:documentation>DE = Germany</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="UK">
				<xs:annotation>
					<xs:documentation>UK = United Kingdom</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="ES">
				<xs:annotation>
					<xs:documentation>ES = Spain</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="PL">
				<xs:annotation>
					<xs:documentation>PL = Poland</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="DK">
				<xs:annotation>
					<xs:documentation>DK = Denmark</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="cropObservations" type="cropObservations"/>
	<xs:complexType name="cropObservations">
		<xs:complexContent>
			<xs:extension base="observations">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="crops" type="crops"/>
	<xs:complexType name="crops">
		<xs:complexContent>
			<xs:extension base="assets">
				<xs:sequence>
					<xs:element name="type" type="codeType" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl263</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="variety" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl232</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="country" type="countryCodeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: ISO country code</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="region" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="useTitle" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl412</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="productionType" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl255</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="productionSequence" type="productionSequenceType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>PRE_CROP = voorteelt, MAIN_CROP = hoofdteelt, FOLLOWUP_CROP = volgteelt, MIXED_CROP = mengteelt</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="regularOrOrganic" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
					<xs:element name="netArea" type="measurementType" minOccurs="0" maxOccurs="1"/>
					<xs:element name="year" type="xs:int" minOccurs="0" maxOccurs="1"/>
					<xs:element name="growEnvironment" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl299</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="growMedium" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl300</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="productionPurpose" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl251</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="productionProtocol" type="codeType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Code list: nl.cl015</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="trackTillage" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
					<xs:element name="deliveries" type="deliveries" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="plots" type="plots" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="tasks" type="tasks" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="dataCropInputs" type="dataCropInputs"/>
	<xs:complexType name="dataCropInputs">
		<xs:sequence>
			<xs:element name="crops" type="crops" minOccurs="1" maxOccurs="1"/>
			<xs:element name="growers" type="growers" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="dataCropRecord" type="dataCropRecord"/>
	<xs:complexType name="dataCropRecord">
		<xs:sequence>
			<xs:element name="crops" type="crops" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="growers" type="growers" minOccurs="0" maxOccurs="1"/>
			<xs:element name="images" type="images" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="binaryFiles" type="binaryFiles" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="deliveries" type="deliveries"/>
	<xs:complexType name="deliveries">
		<xs:annotation>
			<xs:documentation>Delivery of a harvested batch of produce.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Could be the weighing ticket.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="date" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="quantity" type="measurementType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="deliveryLocationId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="deliveryLocationName" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="exterior" type="exterior"/>
	<xs:complexType name="exterior">
		<xs:sequence>
			<xs:element name="linearRing" type="linearRing" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="farms" type="farms"/>
	<xs:complexType name="farms">
		<xs:complexContent>
			<xs:extension base="parties">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="greenhouseLocations" type="greenhouseLocations"/>
	<xs:complexType name="greenhouseLocations">
		<xs:sequence>
			<xs:element name="greenhouseId" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="greenhouseName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="blockId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="hortivationpointBlock" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="postId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="upToPostId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="waterTapId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="xyzReferenceToHotivationPoint" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="growers" type="growers"/>
	<xs:complexType name="growers">
		<xs:complexContent>
			<xs:extension base="parties">
				<xs:sequence>
					<xs:element name="certificats" type="certificats" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="contracts" type="contracts" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="growMediumType" type="growMediumType"/>
	<xs:complexType name="growMediumType">
		<xs:sequence>
			<xs:element name="code" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="images" type="images"/>
	<xs:complexType name="images">
		<xs:sequence>
			<xs:element name="areaIncluded" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="copyrightOwnerName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="digitalImageBinaryObject" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="subject" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="takeDateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="titelName" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="inputAllocations" type="inputAllocations"/>
	<xs:complexType name="inputAllocations">
		<xs:complexContent>
			<xs:extension base="allocations">
				<xs:sequence>
					<xs:element name="compositions" type="compositions" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="treatmentZones" type="treatmentZones" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="interiors" type="interior"/>
	<xs:complexType name="interior">
		<xs:sequence>
			<xs:element name="linearRing" type="linearRing" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="laboratories" type="laboratories"/>
	<xs:complexType name="laboratories">
		<xs:complexContent>
			<xs:extension base="parties">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="languageCodeType">
		<xs:annotation>
			<xs:documentation>Language codes to ISO 639-2:1998. Notation Alpha-3.
http://www.loc.gov/standards/iso639-2/php/code_list.php</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="dan = Danish"/>
			<xs:enumeration value="nld = Dutch"/>
			<xs:enumeration value="fra = French"/>
			<xs:enumeration value="ger = German"/>
			<xs:enumeration value="eng = English"/>
			<xs:enumeration value="spa = Spanish"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="linearRing" type="linearRing"/>
	<xs:complexType name="linearRing">
		<xs:sequence>
			<xs:element name="srsNam" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="srsDimension" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="uomLabels" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="axisLabels" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="count" type="xs:int" minOccurs="0" maxOccurs="1"/>
			<xs:element name="posList" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="measurementType" type="measurementType"/>
	<xs:complexType name="measurementType">
		<xs:annotation>
			<xs:documentation>Standard data type for expressing the value of a measurement. To be used for all types of measurement in this class model.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="unitCode" type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The code that refers to the standard unit or dimension to express the value of this measurement. E.g. KGM for kilogram.
Code list Id: nl.cl020</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="value" type="xs:float" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Expresses the measured value of the measurement.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="observationResults" type="observationResults"/>
	<xs:complexType name="observationResults">
		<xs:sequence>
			<xs:element name="variableCode" type="codeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="value" type="measurementType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="observations" type="observations"/>
	<xs:complexType name="observations">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="dateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="sampleProtocol" type="observationTypeCode" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Code list Id: nl.cl269</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="startDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="endDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="duration" type="xs:int" minOccurs="0" maxOccurs="1"/>
			<xs:element name="method" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="laboratoryAssignedId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="issueDateLaboritory" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="laboratories" type="laboratories" minOccurs="0" maxOccurs="1"/>
			<xs:element name="observationResults" type="observationResults" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="samples" type="samples" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="observationTypeCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CROP"/>
			<xs:enumeration value="SOIL"/>
			<xs:enumeration value="PRODUCE"/>
			<xs:enumeration value="INDOOR_CLIMAT"/>
			<xs:enumeration value="OUTDOOR_WEATHER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="operations" type="operations"/>
	<xs:complexType name="operations">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="area" type="measurementType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Can be a percentage of the total area or an absolute value (like hectare or square meter).</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="startDateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="endDateTime" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
			<xs:element name="status" type="processStatusCode" minOccurs="0" maxOccurs="1"/>
			<xs:element name="thirdPartyId" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="operationTechnique" type="codeType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Code list Id for arable farming: nl.cl127 (or nl.cl293)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="culturalPractice" type="codeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Code list Id for arable farming: nl.cl127 (or nl.cl293)</xs:documentation>
				</xs:annotation>
			</xs:element>			
			<xs:element name="characteristics" type="characteristicType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="border" type="border" minOccurs="0" maxOccurs="1"/>
			<xs:element name="contractors" type="contractors" minOccurs="0" maxOccurs="1"/>
			<xs:element name="inputAllocations" type="inputAllocations" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="observations" type="observations" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="outputAllocations" type="outputAllocations" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="outputAllocations" type="outputAllocations"/>
	<xs:complexType name="outputAllocations">
		<xs:complexContent>
			<xs:extension base="allocations">
				<xs:sequence>
					<xs:element name="treatmentZones" type="treatmentZones" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="parties" type="parties"/>
	<xs:complexType name="parties">
		<xs:sequence>
			<xs:element name="id" type="partyIdType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Identifier of the party.
For companies and organizations AgroConnect codelist CL031 is leading.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="secondaryIds" type="partyIdType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Secondary identifier of the party.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="personName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="phoneNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="telefaxNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="emailAddress" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="iban" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="websiteUrl" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Url of the website of this party.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="postalAddresses" type="postalAddresses" minOccurs="0" maxOccurs="1"/>
			<xs:element name="visitorsAddresses" type="visitorsAddresses" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="partyIdType" type="partyIdType"/>
	<xs:complexType name="partyIdType">
		<xs:annotation>
			<xs:documentation>Generic class to represent the identifier of a party (organization or person). Consist out of two elements; one to refer to the type of scheme that is used for the type of identifier (e.g. a gln, or chamber of commerce number), the second one to represent the value of this identifier.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="type" type="partyIDTypeCodeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Refers to the type of scheme that is used for the type of identifier (e.g. a gln, or chamber of commerce number).
For this, code list CL709 is used. </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Represents the value of the identifier; e.g. the gln number.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="partyIDTypeCodeType">
		<xs:annotation>
			<xs:documentation>Code list for the type of scheme that is used for the type of identifier (e.g. a gln, or chamber of commerce number). For this, code list CL709 is used.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="NL_UBN"/>
			<xs:enumeration value="NL_KVK"/>
			<xs:enumeration value="GS1_GLN"/>
			<xs:enumeration value="CUSNR"/>
			<xs:enumeration value="nl.cl031">
				<xs:annotation>
					<xs:documentation>nl.cl031 = AgroConnect code list</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="VAT">
				<xs:annotation>
					<xs:documentation>Value Added Tax code or number.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="partyRoleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LABORATORY"/>
			<xs:enumeration value="ORDERING_CUSTOMER"/>
			<xs:enumeration value="REPORT_RESULTS_TO"/>
			<xs:enumeration value="INVOICE_TO"/>
			<xs:enumeration value="SAMPLER"/>
			<xs:enumeration value="SENDER_SAMPLES"/>
			<xs:enumeration value="GROWER"/>
			<xs:enumeration value="RECIPIENT_SAMPLES"/>
			<xs:enumeration value="CARRIER_SAMPLES"/>
			<xs:enumeration value="SUPPLIER_SAMPLES"/>
			<xs:enumeration value="OWNER_SAMPLED_OBJECT"/>
			<xs:enumeration value="TRADER"/>
			<xs:enumeration value="LEGAL_OWNER"/>
			<xs:enumeration value="ISSUER_GROWERS_CONTRACT"/>
			<xs:enumeration value="ISSUER_CERTIFICATE"/>
			<xs:enumeration value="FARM"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="plots" type="plots"/>
	<xs:complexType name="plots">
		<xs:complexContent>
			<xs:extension base="assets">
				<xs:sequence>
					<xs:element name="type" type="plotTypeCode" minOccurs="1" maxOccurs="1"/>
					<xs:element name="area" type="measurementType" minOccurs="1" maxOccurs="1"/>
					<xs:element name="regularOrOrganic" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
					<xs:element name="regulatorySoilType" type="codeType" minOccurs="1" maxOccurs="unbounded"/>
					<xs:element name="localSoilType" type="codeType" minOccurs="0" maxOccurs="1"/>
					<xs:element name="border" type="border" minOccurs="0" maxOccurs="1"/>
					<xs:element name="greenhouseLocations" type="greenhouseLocations" minOccurs="0" maxOccurs="1"/>
					<xs:element name="pointLocations" type="pointLocations" minOccurs="0" maxOccurs="1"/>
					<xs:element name="soilObservations" type="soilObservations" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="plotTypeCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CROPFIELD"/>
			<xs:enumeration value="ACTIVITYFIELD"/>
			<xs:enumeration value="TABLE">
				<xs:annotation>
					<xs:documentation>Stationary or mobile platform for growing pot plants in horticulture in a greenhouse.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="pointLocations" type="pointLocations"/>
	<xs:complexType name="pointLocations">
		<xs:sequence>
			<xs:element name="logitude" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="latitude" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="altitude" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="systemId" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="postalAddresses" type="postalAddresses"/>
	<xs:complexType name="postalAddresses">
		<xs:complexContent>
			<xs:extension base="addresses">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="processStatusCode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PROPOSED"/>
			<xs:enumeration value="PLANNED"/>
			<xs:enumeration value="COMPLETED"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="produce" type="produce"/>
	<xs:complexType name="produce">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="producedBatches" type="producedBatches"/>
	<xs:complexType name="producedBatches">
		<xs:complexContent>
			<xs:extension base="assets">
				<xs:sequence>
					<xs:element name="cropIds" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
					<xs:element name="productTypeCode" type="codeType" minOccurs="1" maxOccurs="1"/>
					<xs:element name="cropObservations" type="cropObservations" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="crops" type="crops" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="deliveries" type="deliveries" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="product" type="product"/>
	<xs:complexType name="product">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="productionSequenceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PRE_CROP"/>
			<xs:enumeration value="MAIN_CROP"/>
			<xs:enumeration value="FOLLOWUP_CROP"/>
			<xs:enumeration value="MIXED_CROP"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="samples" type="samples"/>
	<xs:complexType name="samples">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:int" minOccurs="0" maxOccurs="1"/>
			<xs:element name="sampleDate" type="xs:dateTime" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="soilObservations" type="soilObservations"/>
	<xs:complexType name="soilObservations">
		<xs:complexContent>
			<xs:extension base="observations">
				<xs:sequence>
					<xs:element name="soilZoneId" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="soilZoneName" type="xs:string" minOccurs="0" maxOccurs="1"/>
					<xs:element name="verticalLayers" type="verticalLayers" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ORIGINAL"/>
			<xs:enumeration value="UPDATED"/>
			<xs:enumeration value="DELETED"/>
			<xs:enumeration value="COMPLETED"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="tasks" type="tasks"/>
	<xs:complexType name="tasks">
		<xs:annotation>
			<xs:documentation>On the level of a Task, consisting of one to many Operations (sub-processes).</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="startDateTime" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="endDateTime" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>code list: CL256</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="observations" type="observations" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="operations" type="operations" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="treatmentZones" type="treatmentZones"/>
	<xs:complexType name="treatmentZones">
		<xs:sequence>
			<xs:element name="id" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="thirdPartyId" type="xs:int" minOccurs="0" maxOccurs="1"/>
			<xs:element name="charcteristic" type="characteristicType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="area" type="measurementType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="border" type="border" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="verticalLayers" type="verticalLayers"/>
	<xs:complexType name="verticalLayers">
		<xs:annotation>
			<xs:documentation>Expressed in cm.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="relativeBeginHeight" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="relativeEndHeight" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="absoluteBeginHeight" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="absoluteEndHeight" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="visitorsAddresses" type="visitorsAddresses"/>
	<xs:complexType name="visitorsAddresses">
		<xs:complexContent>
			<xs:extension base="addresses">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="weatherObservation" type="weatherObservation"/>
	<xs:complexType name="weatherObservation">
		<xs:complexContent>
			<xs:extension base="observations">
				<xs:sequence/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>